DROP TABLE IF EXISTS troop_config CASCADE;
DROP TABLE IF EXISTS training_grounds_config CASCADE;
DROP TABLE IF EXISTS defence_config CASCADE;
DROP TABLE IF EXISTS town_hall_config CASCADE;
DROP TABLE IF EXISTS resource_config CASCADE;
DROP TABLE IF EXISTS storage_config CASCADE;
DROP TABLE IF EXISTS game_progression_config CASCADE;
DROP TABLE IF EXISTS building_instance CASCADE;
DROP TABLE IF EXISTS battles CASCADE;
DROP TABLE IF EXISTS troops_trained CASCADE;
DROP TABLE IF EXISTS village CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS building_type;
DROP TYPE IF EXISTS battle_result;
DROP TYPE IF EXISTS resource_type;
